apps/dashboard/urls.py
from config.urls import path
from .views import portada, directores

app_name='dash'

urlpatterns=[
    path('',portada,name='portada'),
    path('director/',directores, name='director'),
]

apps/mapas/urls.py
#from django.urls import path
from config.urls import path
from . import views, views2,viewscueradio

app_name='mapas'

urlpatterns=[
    path('filtrado/',views.filtrado,name='filtrado'),
    path('filtrado_list/',views.filtrado_list,name='filtrado_list'),
    path('filter/',views.operaciones_comunes,name='filter'), # type: ignore
    path('listados/',views.filtrar_tablas_view,name='listados'),
    path('puntos/',views2.mapapuntos,name='puntos'), 
    path('filcueradio/',viewscueradio.filtrado_cueradio,name='filcueradio'),
    path('filter_cueradio/',viewscueradio.filter_cueradio,name='filter_cueradio'), # type: ignore
    path('listadomap/',views.filter_listado_map,name='filter_listado_map'), # type: ignore
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import RedirectView, TemplateView
from django.views import defaults as default_views
from apps.dashboard.views import directores
from apps.mapas.views2 import mapapuntos, obtenerdatos
from apps.establecimientos.views import establecimientos
from apps.evaluaciones.views import cargar_respuestas, ver_puntajes
from apps.unidadgestion import views_pers_doc_central
from apps.operativoschaco.views import guardar_examen, examen_guardado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('al/',include('apps.alumnos.urls', namespace='al')),
    path('dash/', directores, name='dash'),
    path('director/',include('apps.directores.urls',namespace='director')),
    path('cargar/', include('apps.archivar.urls', namespace='cargar')),
    path('mapoteca/', include('apps.mapoteca.urls', namespace='mapoteca')),
    path('lex/', include('apps.normativa.urls', namespace='lex')),
    path('mapapuntos/', mapapuntos, name='mapapuntos'),
    path('dibujararea/', obtenerdatos, name='dibujararea'),
    path('login/', include('apps.login.urls', namespace='login')),
    path('portada/', include('apps.dashboard.urls', namespace='portada')),
    path('escuelas/', establecimientos, name='escuelas'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),    
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico')),    
    path('map/', include('apps.mapas.urls', namespace='map')),
    path('usua/', include('apps.usuarios.urls', namespace='usua')),
    path('error_conexion/', TemplateView.as_view(template_name='error_conexion.html'), name='error_conexion'),
    path('consulta_vacia/', TemplateView.as_view(template_name='consulta_vacia.html'), name='consulta_vacia'),
    path('repo/', include('apps.reportes.urls', namespace='repo')),    
    path('videoteca/', include('apps.videoteca.urls', namespace='videoteca')),   
    path('acceso/',include('apps.regacceso.urls', namespace='acceso')),
    path('lect/',include('apps.lectocomp.urls',namespace='lect')),
    path('indicador/',include('apps.indicadores.urls',namespace='indicador')),
    path('doc/',include('apps.asistendoc.urls',namespace='doc')),   
    path('censo/',include('apps.cenpe.urls',namespace='censo')) ,
    path('operativo/',include('apps.oplectura.urls', namespace='operativo')),
    path('super/',include('apps.supervisores.urls', namespace='super')), 
    path('sup/',include('apps.superescuela.urls', namespace='sup')),    
    path('contador/',include('apps.cuenta_regresiva.urls',namespace='contador')),
    path('organica/',include('apps.pof.urls',namespace='organica')),
    path('select2/', include('django_select2.urls')),       
    path('evaluacion/<int:alumno_id>/<int:evaluacion_id>/', cargar_respuestas, name='cargar_respuestas'),
    path('puntajes/<int:alumno_id>/', ver_puntajes, name='ver_puntajes'),
    path('evaluaciones/',include('apps.evaluaciones.urls',namespace='evaluaciones')),
    path('central/',include('apps.unidadgestion.urls',namespace='central')),
    path('uegp/',include('apps.uegp.urls',namespace='uegp')),
    path('chaco/',include('apps.funcionarios.urls',namespace='chaco')),
    path('rl/',include('apps.represlegales.urls',namespace='rl')),
    path('indigena/',include('apps.intercultural.urls',namespace='indigena')),
    path('bbl/',include('apps.biblioteca.urls',namespace='bbl')),
    path('indic/',include('apps.indicadoresie.urls',namespace='indic')),
    path('infra/',include('apps.infraestructura.urls',namespace='infra')), 
    path('pregunta/',include('apps.operativoschaco.urls',namespace='pregunta')), 
    path('examendiag/',include('apps.operativchaco.urls',namespace='examendiag')),
    path('consultas/', include('apps.consultas.urls', namespace='consultas_api')),
    path('ayuda/', include('apps.ayudarenpe.urls', namespace='ayuda')),
    path('evaluaciones_educativas/', include('apps.evaluaciones_educativas.urls', namespace='evaluaciones_educativas')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

apps/mapas/models.py
from django.db import models
from django.contrib.gis.db import models

class VCapaUnicaOfertas(models.Model):
    cueanexo = models.BigIntegerField(blank=True, null=True)
    geom = models.GeometryField(blank=True, null=True)  
    long = models.FloatField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)
    nom_est = models.CharField(blank=True, null=True)
    padron_cueanexo = models.IntegerField(blank=True, null=True)
    acronimo = models.TextField(blank=True, null=True)
    oferta = models.TextField(blank=True, null=True)
    etiqueta = models.TextField(blank=True, null=True)
    nro_est = models.CharField(blank=True, null=True)
    ambito = models.CharField(blank=True, null=True)
    sector = models.CharField(blank=True, null=True)
    region_loc = models.CharField(blank=True, null=True)
    ref_loc = models.CharField(blank=True, null=True)
    calle = models.CharField(blank=True, null=True)
    numero = models.CharField(blank=True, null=True)
    localidad = models.CharField(blank=True, null=True)
    departamento = models.CharField(blank=True, null=True)
    estado_loc = models.TextField(blank=True, null=True)
    est_oferta = models.TextField(blank=True, null=True)
    estado_est = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'v_capa_unica_ofertas'

apps/regionales/models.py
from django.db import models

# Create your models here.

apps/mapas/forms.py
from django import forms

"""
Este módulo define un formulario de filtrado que permite seleccionar niveles, localidades y establecimientos. 
Está diseñado para ser utilizado con campos de selección dinámicamente cargados.

Clases:
    FiltroFormularioRadio: Formulario con tres campos de selección (nivel, localidad, establecimiento) que 
                           se rellenan dinámicamente con opciones desde el servidor.
"""

class FiltroFormularioRadio(forms.Form):
    """
    Formulario para filtrar por nivel, localidad y establecimiento.

    Atributos:
        nivel (ChoiceField): Campo de selección para los niveles, que se rellena dinámicamente.
        localidad (ChoiceField): Campo de selección para las localidades, que se rellena dinámicamente.
        establecimiento (ChoiceField): Campo de selección para los establecimientos, que se rellena dinámicamente.
    """
    nivel = forms.ChoiceField(
        choices=[],  # Las opciones se cargan dinámicamente
        widget=forms.Select(attrs={'class': 'form-select', 'id': 'nivel-select'})
    )
    localidad = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={'class': 'form-select', 'id': 'localidad-select'})
    )
    establecimiento = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={'class': 'form-select', 'id': 'establecimiento-select'})
    )

apps/mapas/views.py
import json
import psycopg2
import asyncpg
import asyncio
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

def filtrado(request):    
    return render(request, 'mapa/filter.html')

def filtrado_list(request):
    return render(request,'mapa/filter_listadomap.html')

@csrf_exempt
def operaciones_comunes(request, template_name='publico/basecriterios.html'):   
    if request.method == 'POST':
        cueanexo = request.POST.get('Cueanexo')
        ambito = request.POST.get('Ambito')
        sector = request.POST.get('Sector')
        region = request.POST.get('Region')
        departamento = request.POST.get('Departamento')
        localidad = request.POST.get('Localidad')
        oferta = request.POST.get('Oferta')

        print("Parámetros de la solicitud:", ambito, sector, localidad, oferta)

        # Conectarse a la base de datos
        connection = psycopg2.connect(
            host='relevamientoanual.com.ar',            
            user='visualizador',
            password='Estadisticas24',
            database='visualizador'
        )

        # Realizar la consulta en la base de datos
        cursor = connection.cursor()
        query = "SELECT cueanexo, lat, long, nom_est, oferta, ambito, sector, region_loc, calle, numero, localidad FROM v_capa_unica_ofertas WHERE 1=1 "
        parameters = []
        if cueanexo:
            query += "AND cueanexo = %s"
            parameters.append(cueanexo)
        if ambito:
            query += " AND ambito = %s"
            parameters.append(ambito)
        if sector:
            query += " AND sector = %s"
            parameters.append(sector)
        if region:
            query += " AND region_loc = %s"
            parameters.append(region)
        if departamento:
            query += " AND departamento = %s"
            parameters.append(departamento)
        if localidad:
            query += "AND localidad = %s"
            parameters.append(localidad)
        if oferta:
            query += "AND acronimo LIKE %s"
            parameters.append('%'+oferta+'%')

        cursor.execute(query, parameters)
        rows = cursor.fetchall()

        # Filtrar los marcadores con latitud y longitud distintas de 0 o vacías
        filtered_rows = [(cueanexo, lat, lng, nom_est, oferta, ambito, sector, region_loc, calle, numero, localidad) 
                         for cueanexo, lat, lng, nom_est, oferta, ambito, sector, region_loc, calle, numero, localidad in rows 
                         if lat != 0 and lng != '' and lng != 0 and lat != '']

        # Obtener los nombres de las columnas
        column_names = [desc[0] for desc in cursor.description] # type: ignore
        filtered_rows = [row for row in rows if row[1] != 0 and row[2] != 0]

        # Cerrar la conexión a la base de datos
        cursor.close()
        connection.close()

        context = {
            'title': 'Mapa',
            'data_json': json.dumps(filtered_rows),
            'column_names_json': json.dumps(column_names)
        }

        print("Contexto en operaciones_comunes:", context)

        if template_name == 'publico/basecriterios.html':
            return render (request,template_name,context)
        elif template_name == 'publico/listadomap.html':
            return render(request,template_name,context)
        else:
            return render(request,template_name,context)
        
def filter_data(request):
    context = operaciones_comunes(request, template_name='publico/basecriterios.html')
    print("Contexto en filter_data:", context)
    return render(request, 'mapa/ofertasmark.html', context if isinstance(context, dict) else None)

def filter_listado_map(request):
    context = operaciones_comunes(request, template_name='publico/listadomap.html')
    return context


    
#####################################################################
#      PARA MOSTRAR DATOS MARCADOR SELLECIONADO EN EL MAPA          #
#####################################################################
async def filtrar_tablas_view(request):      
    
    
    cueanexo = request.GET.get('cueanexo')

    # Validar y sanitizar el valor de cueanexo
    if cueanexo is None:
        # Manejar el caso si no se proporciona cueanexo
        return render(request, 'error.html', {'mensaje': 'No se proporcionó el parámetro cueanexo'})

    # Establecer la conexión a la base de datos
    try:
        connection = await asyncpg.connect(
            host='relevamientoanual.com.ar',
            user='visualizador',
            password='Estadisticas24',
            database='Padron'
        )
    except asyncpg.PostgresError as e:
        # Manejar el error de conexión
        return render(request, 'error.html', {'mensaje': 'Error al conectar a la base de datos'})

    # Construir y ejecutar la consulta SQL para obtener los datos de las dos tablas
    
    institucional = """
        SELECT categoria, jornada, oferta, id_establecimiento, ref_loc, calle, numero, anexo,apellido_resp, nombre_resp, resploc_telefono,resploc_email,
            sup_tecnico, email_suptecnico, tel_suptecnico
        FROM padron_ofertas        
        WHERE cueanexo = $1 
    """ 
    planes="""
        SELECT titulo, orientacion
        FROM v_planes_estudio
        WHERE CONCAT(cue,anexo)=$1
    """

    # Construir y ejecutar la consulta SQL para obtener los datos de las dos tablas
    anexos = """
        SELECT DISTINCT po.anexo, po.calle, po.numero, po.estado_loc
        FROM padron_ofertas po
        WHERE po.id_establecimiento IN (
            SELECT id_establecimiento
            FROM padron_ofertas
            WHERE cueanexo = $1 
        ) AND po.estado_loc = $2
    """
    ofertas = """
        SELECT anexo, calle, numero, cueanexo, oferta, est_oferta
        FROM padron_ofertas
        WHERE cueanexo = $1 AND est_oferta = $2        
    """
    params = [cueanexo]
    params2= [cueanexo,'Activo']

    try:
        resultados = await connection.fetch(institucional, *params)
        resultados1=await connection.fetch(planes,*params)    
        resultados2=await connection.fetch(anexos, *params2) 
        resultados3=await connection.fetch(ofertas, *params2)   
        #print(resultados)
        #print(resultados1)
        print(resultados2)
        
    except asyncpg.PostgresError as e:
        # Manejar el error de consulta
        await connection.close()
        return render(request, 'error.html', {'mensaje': 'Error al ejecutar la consulta'})

    # Cerrar la conexión a la base de datos
    await connection.close()    
    
    return render(request, 'mapa/otro_template.html', {'resultados': resultados, 'resultados1':resultados1, 'resultados2':resultados2, 'resultados3':resultados3})

apps/regionales/views.py
from django.shortcuts import render
from django.contrib.gis.geos import Point, Polygon
from shapely.geometry import shape
import json

def regionalesview(request):
    # Cargar el archivo GeoJSON
    with open('Regiones.geojson', 'r') as f:
        geojson_data = json.load(f)

    # Obtener las características (features) del GeoJSON
    features = geojson_data['features']

    # Lista para almacenar las coordenadas de los polígonos
    perimeter_coords = []

    # Iterar sobre las características y extraer las coordenadas de los polígonos
    for feature in features:
        geometry = feature['geometry']
        # Convertir la geometría en un objeto shapely
        shapely_geom = shape(geometry)
        # Si la geometría es un MultiPolygon, extraer las coordenadas
        if shapely_geom.geom_type == 'MultiPolygon':
            for polygon in shapely_geom.geoms:  # Utilizamos la propiedad geoms
                perimeter_coords.append(list(polygon.exterior.coords))
        # Si es un Polygon, solo hay un conjunto de coordenadas
        elif shapely_geom.geom_type == 'Polygon':
            perimeter_coords.append(list(shapely_geom.exterior.coords))
        print(perimeter_coords)
    return render(request, 'mapa/regionales.html', {'perimeter_coords': perimeter_coords})

templates/mapa/colectivos.html
{% extends 'dashboard/body.html' %}

{% load static %}

{% block content %}
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.Default.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-measure/dist/leaflet-measure.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <style>
        #map-container {
            position: relative;
        }
        #map {
            height: 550px;
        }
    </style>
</head>
<body>
    {% block content_header %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark"></h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'dash:portada' %}">Regresar</a></li>                                    
                    </ol>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <h2>Ubicación Geográfica de CUE N°: {{cueanexo}} y los cercanos en un radio de: {{radio}} metros</h2>
    <div id="map-container">
        <div id="map"></div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.js"></script>
    <script src="https://unpkg.com/esri-leaflet@3.0.2/dist/esri-leaflet.js"
    integrity="sha512-myckXhaJsP7Q7MZva03Tfme/MSF5a6HC2xryjAM4FxPLHGqlh5VALCbywHnzs2uPoF/4G/QVXyYDDSkp5nPfig=="
    crossorigin=""></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/leaflet.markercluster.js"></script>
    <script src="https://unpkg.com/leaflet-measure/dist/leaflet-measure.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
    <script>
        var map = L.map('map').setView([{{ center_lat }}, {{ center_lng }}], 13);  
        var bounds = L.latLngBounds();
        var blueMarkers = L.layerGroup(); 
        var blackMarkers = L.layerGroup(); 

        // Configuración del mapa base
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
            maxZoom: 18,
        }).addTo(map);

        // Iterar sobre los datos de Cueanexos y agregar al mapa
        var cueanexoData = JSON.parse('{{ cueanexo_data|escapejs }}');
        for (var i = 0; i < cueanexoData.length; i++) {
            var lat = cueanexoData[i][1];
            var lng = cueanexoData[i][2];
            var cueanexoMarker = cueanexoData[i][0];
            var nom_est = cueanexoData[i][3];
            var oferta = cueanexoData[i][4];
            var ambito = cueanexoData[i][5];
            var sector = cueanexoData[i][6];
            var region_loc = cueanexoData[i][7];
            var calle = cueanexoData[i][8];
            var numero = cueanexoData[i][9];
            var localidad = cueanexoData[i][10];
            var markerColor = 'blue';
            console.log(lat, lng)
            if (lat !== 0 && lng !== '') {
                var markerIcon = L.icon({
                    iconUrl: "{% static 'img/' %}" + markerColor + ".png",
                    iconSize: [25, 41],
                    iconAnchor: [12, 41],
                    popupAnchor: [1, -34],
                    tooltipAnchor: [16, -28]
                });

                var marker = L.marker([lat, lng], { icon: markerIcon });
                marker.bindPopup(
                    '<strong>Cueanexo:</strong> ' + cueanexoMarker + '<br>' +
                    '<strong>Establecimiento:</strong> ' + nom_est + '<br>' +
                    '<strong>Ofertas:</strong> ' + oferta + '<br>' +
                    '<strong>Ámbito:</strong> ' + ambito + '<br>' +
                    '<strong>Sector:</strong> ' + sector + '<br>' +
                    '<strong>Región Educativa:</strong> ' + region_loc + '<br>' +
                    '<strong>Calle:</strong> ' + calle + ' ' +
                    '<strong>Nro:</strong> ' + numero + ' - ' + localidad + '<br>'
                );
                blueMarkers.addLayer(marker);
                bounds.extend(marker.getLatLng());
            }
        }

        // Iterar sobre los datos de Colectivos y agregar al mapa
        var colectivosData = JSON.parse('{{ colectivos_data|escapejs }}');
        for (var i = 0; i < colectivosData.length; i++) {
            var lat = colectivosData[i][2];
            var lng = colectivosData[i][3];
            var codigo = colectivosData[i][0];
            var direccion = colectivosData[i][1];
            var lineas = colectivosData[i][4];
            var markerColor = 'black';

            if (lat !== 0 && lng !== '') {
                var markerIcon = L.icon({
                    iconUrl: "{% static 'img/' %}" + markerColor + ".png",
                    iconSize: [25, 41],
                    iconAnchor: [12, 41],
                    popupAnchor: [1, -34],
                    tooltipAnchor: [16, -28]
                });

                var marker = L.marker([lat, lng], { icon: markerIcon });
                marker.bindPopup(
                    '<strong>Código:</strong> ' + codigo + '<br>' +
                    '<strong>Dirección:</strong> ' + direccion + '<br>' +
                    '<strong>Líneas:</strong> ' + lineas + '<br>'
                );
                blackMarkers.addLayer(marker);
                bounds.extend(marker.getLatLng());
            }
        }

        map.addLayer(blueMarkers); 
        map.addLayer(blackMarkers); 
        map.fitBounds(bounds);

        // Añadir control de capas
        L.control.layers(null, {
            "Cue buscado": blueMarkers,
            "Colectivos": blackMarkers 
        }).addTo(map);

        // Añadir círculo de radio
        var center_lat = parseFloat('{{ center_lat }}'.replace(',', '.'));
        var center_lng = parseFloat('{{ center_lng }}'.replace(',', '.'));
        var radio = parseInt('{{ radio }}');

        L.circle([center_lat, center_lng], {
            color: 'red',
            fillColor: 'red',
            fillOpacity: 0.2,
            radius: radio
        }).addTo(map);
    </script>
</body>
{% endblock %}

templates/mapa/index.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC' crossorigin='anonymous'>
    <title>Document</title>
    <style>
        .hidden {
            display: none;
        }
    </style>
</head>
<body>
    <div class='form-check form-switch'>
        <input class='form-check-input' type='checkbox' id='SwitchCheckAmbito' onchange='toggleDropdown('Ambito')'>
        <label class='form-check-label' for='SwitchCheckAmbito'>Ámbito</label>
        <select class='form-select hidden' id='AmbitoDropdown' disabled>
            <option value='Urbano'>Urbano</option>
            <option value='Rural Disperso'>Rural Disperso</option>
            <option value='Rural Aglomerado'>Rural Aglomerado</option>
        </select>
    </div>
    <div class='form-check form-switch'>
        <input class='form-check-input' type='checkbox' id='SwitchCheckSector' onchange='toggleDropdown('Sector')'>
        <label class='form-check-label' for='SwitchCheckSector'>Sector</label>
        <select class='form-select hidden' id='SectorDropdown' disabled>
            <option value='Estatal'>Estatal</option>
            <option value='Privado'>Privado</option>
            <option value='Gestión Social'>Gestión Social</option>
        </select>
    </div>
    <div class='form-check form-switch'>
        <input class='form-check-input' type='checkbox' id='SwitchCheckRegion' onchange='toggleDropdown('Region')'>
        <label class='form-check-label' for='SwitchCheckRegion'>Región</label>
        <select class='form-select hidden' id='RegionDropdown' disabled>
            <option value='R.E. 10-A'>1</option>
            <option value='2'>2</option>
            <option value='3'>3</option>
            <!-- Agrega más opciones de regiones si es necesario -->
        </select>
    </div>
    <div class='form-check form-switch'>
        <input class='form-check-input' type='checkbox' id='SwitchCheckDepartamento' onchange='toggleDropdown('Departamento')'>
        <label class='form-check-label' for='SwitchCheckDepartamento'>Departamento</label>
        <select class='form-select hidden' id='DepartamentoDropdown' disabled>
            <option value='SAN FERNANDO'>SAN FERNANDO</option>
            <option value='Eva Perón'>Eva Perón</option>
            <option value='Sargento Cabral'>Sargento Cabral</option>
            <!-- Agrega más opciones de departamentos si es necesario -->
        </select>
    </div>

    <button onclick='sendFormData()'>Enviar</button>
    <button onclick='resetForm()'>Limpiar</button>

    <script>
        // Guarda los valores iniciales de los switches
        const initialSwitchStates = {
            'Ambito': false,
            'Sector': false,
            'Region': false,
            'Departamento': false
        };

        // Espera a que el DOM esté completamente cargado
        document.addEventListener('DOMContentLoaded', function() {
            // Desactiva los dropdowns al cargar el template
            toggleDropdown('Ambito');
            toggleDropdown('Sector');
            toggleDropdown('Region');
            toggleDropdown('Departamento');
        });

        function toggleDropdown(id) {
            const switchElement = document.getElementById(`SwitchCheck${id}`);
            const dropdown = document.getElementById(`${id}Dropdown`);

            if (switchElement.checked) {
                dropdown.classList.remove('hidden');
                dropdown.disabled = false;
            } else {
                dropdown.classList.add('hidden');
                dropdown.disabled = true;
            }
        }

        function sendFormData() {
            const ambitoDropdown = document.getElementById('AmbitoDropdown');
            const sectorDropdown = document.getElementById('SectorDropdown');
            const regionDropdown = document.getElementById('RegionDropdown');
            const departamentoDropdown = document.getElementById('DepartamentoDropdown');

            const ambito = ambitoDropdown.value;
            const sector = sectorDropdown.value;
            const region = regionDropdown.value;
            const departamento = departamentoDropdown.value;

            const url = `/mapas/get_filtered_rows?ambito=${ambito}&sector=${sector}&region=${region}&departamento=${departamento}`;

            // Realiza la solicitud GET al servidor usando fetch()
            fetch(url)
                .then(response => {
                    // Verifica si la respuesta del servidor es exitosa
                    if (response.ok) {
                        // Aquí puedes manejar la respuesta exitosa del servidor
                        console.log('Solicitud enviada con éxito');
                    } else {
                        // Aquí puedes manejar la respuesta de error del servidor
                        console.error('Error en la solicitud');
                    }
                })
                .catch(error => {
                    // Aquí puedes manejar errores de red u otros errores relacionados con la solicitud
                    console.error('Error en la solicitud', error);
                });
        }
        
        function resetForm() {
            // Restaura los switches a sus valores iniciales
            Object.keys(initialSwitchStates).forEach(function(id) {
                const switchElement = document.getElementById(`SwitchCheck${id}`);
                switchElement.checked = initialSwitchStates[id];
                toggleDropdown(id);
            });

            // Restaura los valores de los dropdowns
            const dropdowns = document.getElementsByClassName('form-select');
            for (let i = 0; i < dropdowns.length; i++) {
                dropdowns[i].selectedIndex = 0;
            }
        }
    </script>
</body>
</html>