apps/biblioteca/urls.py
from django.urls import path
from .views_matbiblio import (
    MaterialBibliograficoCreateView,
    MaterialBibliograficoUpdateView,
    MaterialBibliograficoDeleteView,
    MaterialBibliograficoListView
)

from .views_servref import (
    ServiciosReferenciaCreateView,
    ServiciosReferenciaUpdateView,
    ServiciosReferenciaDeleteView,
    ServiciosReferenciaListView
)

from .views_servrefvirtual import (
    ServiciosRefVirtualCreateView,
    ServiciosRefVirtualUpdateView,
    ServiciosRefVirtualDeleteView,
    ServiciosRefVirtualListView
)

from .views_servprestamo import (
    ServiciosPrestamoCreateView,
    ServiciosPrestamoUpdateView,
    ServiciosPrestamoDeleteView,
    ServiciosPrestamoListView
)

from .views_infopedag import (
    InfoPedagoCreateView,
    InfoPedagoUpdateView,
    InfoPedagoDeleteView,
    InfoPedagoListView
)

from .views_instituciones import (
    InstitucionesCreateView,
    InstitucionesUpdateView,
    InstitucionesDeleteView,
    InstitucionesListView
)

from .views_asistusua import (
    AsistUsuarioCreateView,
    AsistUsuaUpdateView,
    AsistUsuaDeleteView,
    AsistUsuaListView
)

from .views_proctec import (
    ProcTecCreateView,
    ProcTecUpdateView,
    ProcTecDeleteView,
    ProcTecListView
)

from .views_aguapey import (
    AguapeyCreateView,
    AguapeyUpdateView,
    AguapeyDeleteView,
    AguapeyListView
)

from .views_list_docnodoc import (
    DocentePonMensualListView,
    NoDocentePonMensualListView
)


from .views_generarpdf import generar_pdf_material_bibliografico
from .views_instituciones import ObtenerEscuelaView
from .views_generarinforme import GenerarInformeView
from .views_planillasanexas import PlanillasAnexasView, PlanillasAnexasListView, PlanillasAnexasUpdateView, PlanillasAnexasDeleteView
from .views_dashboard import DashboardView, DashboardDirView
from .views_reporteinformes import generar_informe_list, generar_informe
from .views_cuemesanio import generar_pdf_cuemesanio, modal_generar_pdf_cuemesanio
from .views_cuemesanio_uno import generar_pdf_cuemesanio_uno, modal_generar_pdf_cuemesanio_uno
from .views_registrofondos import RegistroDestinoFondosView, RegistroDestinoFondosListView, RegistroDestinoFondosDeleteView
from .views import (
    servicio_prestamo_view, 
    filtrar_servicio_prestamo, 
    filtrar_mat_biblio, 
    servicio_matbiblio_view,
    filtrar_servicio_referencia,
    servicio_referencia_view,
    servicio_referencia_virtual_view,
    filtrar_servicio_referencia_virtual,
    informe_pedagogico_view,
    filtrar_informe_pedagogico,
    asistencia_usuario_view,
    filtrar_asistencia_usuario,
    proceso_tecnico_view,
    filtrar_proceso_tecnico,
    destino_fondos_view,
    filtrar_destino_fondos,
    planillas_anexas_view,
    filtrar_planillas_anexas,
    filtrar_personal_bibliotecario,
    personal_bibliotecario_view
)

from .views_bibliotecarios import (
    BibliotecariosCueCreateView,
    BibliotecariosCueListView,
    BibliotecariosCueUpdateView,
    BibliotecariosCueDeleteView,
)

app_name = 'bibliotecas'

urlpatterns = [
    # Material Bibliográfico
    path('materialbibliografico/list/', MaterialBibliograficoListView.as_view(), name='materialbibliografico_list'),
    path('materialbibliografico/add/', MaterialBibliograficoCreateView.as_view(), name='materialbibliografico_create'),
    path('materialbibliografico/update/<int:pk>/', MaterialBibliograficoUpdateView.as_view(), name='materialbibliografico_update'),
    path('materialbibliografico/delete/<int:pk>/', MaterialBibliograficoDeleteView.as_view(), name='materialbibliografico_delete'),

    # Servicios de Referencia
    path('servref/list/', ServiciosReferenciaListView.as_view(), name='servref_list'),
    path('servref/add/', ServiciosReferenciaCreateView.as_view(), name='servref_create'),
    path('servref/update/<int:pk>/', ServiciosReferenciaUpdateView.as_view(), name='servref_update'),
    path('servref/delete/<int:pk>/', ServiciosReferenciaDeleteView.as_view(), name='servref_delete'),
    
    # Servicios de Referencia Virtual
    path('servrefvirtual/list/', ServiciosRefVirtualListView.as_view(), name='servrefvirtual_list'),
    path('servrefvirtual/add/', ServiciosRefVirtualCreateView.as_view(), name='servrefvirtual_create'),
    path('servrefvirtual/update/<int:pk>/', ServiciosRefVirtualUpdateView.as_view(), name='servrefvirtual_update'),
    path('servrefvirtual/delete/<int:pk>/', ServiciosRefVirtualDeleteView.as_view(), name='servrefvirtual_delete'),
    
    # Servicios de Préstamos
    path('servprestamo/list/', ServiciosPrestamoListView.as_view(), name='servprestamo_list'),
    path('servprestamo/add/', ServiciosPrestamoCreateView.as_view(), name='servprestamo_create'),
    path('servprestamo/update/<int:pk>/', ServiciosPrestamoUpdateView.as_view(), name='servprestamo_update'),
    path('servprestamo/delete/<int:pk>/', ServiciosPrestamoDeleteView.as_view(), name='servprestamo_delete'),
    
    # Informe Pedagógico
    path('infopedago/list/', InfoPedagoListView.as_view(), name='infopedago_list'),
    path('infopedago/add/', InfoPedagoCreateView.as_view(), name='infopedago_create'),
    path('infopedago/update/<int:pk>/', InfoPedagoUpdateView.as_view(), name='infopedago_update'),
    path('infopedago/delete/<int:pk>/', InfoPedagoDeleteView.as_view(), name='infopedago_delete'),
    
    # Instituciones
    path('instituciones/list/', InstitucionesListView.as_view(), name='instituciones_list'),
    path('instituciones/add/', InstitucionesCreateView.as_view(), name='instituciones_create'),
    path('instituciones/update/<int:pk>/', InstitucionesUpdateView.as_view(), name='instituciones_update'),
    path('instituciones/delete/<int:pk>/', InstitucionesDeleteView.as_view(), name='instituciones_delete'),
    
    # Asistencia Usuarios
    path('asistusua/list/', AsistUsuaListView.as_view(), name='asistusua_list'),
    path('asistusua/add/', AsistUsuarioCreateView.as_view(), name='asistusua_create'),
    path('asistusua/update/<int:pk>/', AsistUsuaUpdateView.as_view(), name='asistusua_update'),
    path('asistusua/delete/<int:pk>/', AsistUsuaDeleteView.as_view(), name='asistusua_delete'),
    
    # Procesos Técnicos
    path('proctec/list/', ProcTecListView.as_view(), name='proctec_list'),
    path('proctec/add/', ProcTecCreateView.as_view(), name='proctec_create'),
    path('proctec/update/<int:pk>/', ProcTecUpdateView.as_view(), name='proctec_update'),
    path('proctec/delete/<int:pk>/', ProcTecDeleteView.as_view(), name='proctec_delete'),
    
    # Aguapey
    path('aguapey/list/', AguapeyListView.as_view(), name='aguapey_list'),
    path('aguapey/add/', AguapeyCreateView.as_view(), name='aguapey_create'),
    path('aguapey/update/<int:pk>/', AguapeyUpdateView.as_view(), name='aguapey_update'),
    path('aguapey/delete/<int:pk>/', AguapeyDeleteView.as_view(), name='aguapey_delete'),
    
    # Registro Destino de Fondos
    path('regfondos/', RegistroDestinoFondosView.as_view(), name='regfondos'),
    path('regfondos_list/', RegistroDestinoFondosListView.as_view(), name='regfondos_list'),
    path('regfondos/delete/<int:pk>/', RegistroDestinoFondosDeleteView.as_view(), name='regfondos   _delete'),
    
    # Planillas Anexas
    path('plan_anexas/', PlanillasAnexasView.as_view(), name='plan_anexas'),
    path('anexas_list/', PlanillasAnexasListView.as_view(), name='anexas_list'),
    path('anexas/update/<int:pk>/', PlanillasAnexasUpdateView.as_view(), name='anexas_update'),
    path('anexas/delete/<int:pk>/', PlanillasAnexasDeleteView.as_view(), name='anexas_delete'),
    
    # Planillas Docentes y no Docentes
    path('nom_doc/', DocentePonMensualListView.as_view(), name='nom_doc'),
    path('nom_ndoc/', NoDocentePonMensualListView.as_view(), name='nom_ndoc'), 
    
    # home 
    path('generar_pdf/', generar_pdf_material_bibliografico, name='generar_pdf'),
    path('obtener_escuela/', ObtenerEscuelaView.as_view(), name='obtener_escuela'),
    path('generar_info/', GenerarInformeView.as_view(), name='generar_info'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard_dir/', DashboardDirView.as_view(), name='dashboard_dir'),
    path('generar_informe_list/', generar_informe_list, name='generar_informe_list'),
    path('generar_informe/', generar_informe, name='generar_informe'),
    path('generar_pdf_cue/', generar_pdf_cuemesanio, name='generar_pdf_cue'),
    path('modal_generar_pdf_cue/', modal_generar_pdf_cuemesanio, name='modal_generar_pdf_cue'),
    path('generar_pdf_uno/', generar_pdf_cuemesanio_uno, name='generar_pdf_uno'),
    path('modal_generar_pdf_uno/', modal_generar_pdf_cuemesanio_uno, name='modal_generar_pdf_uno'),

    # Resultados
    path("servicio_prestamo/", servicio_prestamo_view, name="servicio_prestamo"),
    path("filtrar_servicio_prestamo/", filtrar_servicio_prestamo, name="filtrar_servicio_prestamo"),
    path("servicio_matbiblio/", servicio_matbiblio_view, name="servicio_matbiblio"),
    path("filtrar_matbiblio/", filtrar_mat_biblio, name="filtrar_matbiblio"),
    path("servicio_referencia/", servicio_referencia_view, name="servicio_referencia"),
    path("filtrar_referencia/", filtrar_servicio_referencia, name="filtrar_referencia"),
    path("servicio_refvirtual/", servicio_referencia_virtual_view, name="servicio_refvirtual"),
    path("filtrar_refvirtual/", filtrar_servicio_referencia_virtual, name="filtrar_refvirtual"),
    path("infopedagres/", informe_pedagogico_view, name="infopedagres"),
    path("filtrar_infopedag/", filtrar_informe_pedagogico, name="filtrar_infopedag"),
    path("asist_usua/", asistencia_usuario_view, name="asist_usua"),
    path("filtrar_asisusua/", filtrar_asistencia_usuario, name="filtrar_asisusua"),
    path("proctecres/", proceso_tecnico_view, name="proctecres"),
    path("filtrar_proctec/", filtrar_proceso_tecnico, name="filtrar_proctec"),
    path("destinofondos/", destino_fondos_view, name="destinofondos"),

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import RedirectView, TemplateView
from django.views import defaults as default_views
from apps.dashboard.views import directores
from apps.mapas.views2 import mapapuntos, obtenerdatos
from apps.establecimientos.views import establecimientos
from apps.evaluaciones.views import cargar_respuestas, ver_puntajes
from apps.unidadgestion import views_pers_doc_central
from apps.operativoschaco.views import guardar_examen, examen_guardado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('al/',include('apps.alumnos.urls', namespace='al')),
    path('dash/', directores, name='dash'),
    path('director/',include('apps.directores.urls',namespace='director')),
    path('cargar/', include('apps.archivar.urls', namespace='cargar')),
    path('mapoteca/', include('apps.mapoteca.urls', namespace='mapoteca')),
    path('lex/', include('apps.normativa.urls', namespace='lex')),
    path('mapapuntos/', mapapuntos, name='mapapuntos'),
    path('dibujararea/', obtenerdatos, name='dibujararea'),
    path('login/', include('apps.login.urls', namespace='login')),
    path('portada/', include('apps.dashboard.urls', namespace='portada')),
    path('escuelas/', establecimientos, name='escuelas'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),    
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico')),    
    path('map/', include('apps.mapas.urls', namespace='map')),
    path('usua/', include('apps.usuarios.urls', namespace='usua')),
    path('error_conexion/', TemplateView.as_view(template_name='error_conexion.html'), name='error_conexion'),
    path('consulta_vacia/', TemplateView.as_view(template_name='consulta_vacia.html'), name='consulta_vacia'),
    path('repo/', include('apps.reportes.urls', namespace='repo')),    
    path('videoteca/', include('apps.videoteca.urls', namespace='videoteca')),   
    path('acceso/',include('apps.regacceso.urls', namespace='acceso')),
    path('lect/',include('apps.lectocomp.urls',namespace='lect')),
    path('indicador/',include('apps.indicadores.urls',namespace='indicador')),
    path('doc/',include('apps.asistendoc.urls',namespace='doc')),   
    path('censo/',include('apps.cenpe.urls',namespace='censo')) ,
    path('operativo/',include('apps.oplectura.urls', namespace='operativo')),
    path('super/',include('apps.supervisores.urls', namespace='super')), 
    path('sup/',include('apps.superescuela.urls', namespace='sup')),    
    path('contador/',include('apps.cuenta_regresiva.urls',namespace='contador')),
    path('organica/',include('apps.pof.urls',namespace='organica')),
    path('select2/', include('django_select2.urls')),       
    path('evaluacion/<int:alumno_id>/<int:evaluacion_id>/', cargar_respuestas, name='cargar_respuestas'),
    path('puntajes/<int:alumno_id>/', ver_puntajes, name='ver_puntajes'),
    path('evaluaciones/',include('apps.evaluaciones.urls',namespace='evaluaciones')),
    path('central/',include('apps.unidadgestion.urls',namespace='central')),
    path('uegp/',include('apps.uegp.urls',namespace='uegp')),
    path('chaco/',include('apps.funcionarios.urls',namespace='chaco')),
    path('rl/',include('apps.represlegales.urls',namespace='rl')),
    path('indigena/',include('apps.intercultural.urls',namespace='indigena')),
    path('bbl/',include('apps.biblioteca.urls',namespace='bbl')),
    path('indic/',include('apps.indicadoresie.urls',namespace='indic')),
    path('infra/',include('apps.infraestructura.urls',namespace='infra')), 
    path('pregunta/',include('apps.operativoschaco.urls',namespace='pregunta')), 
    path('examendiag/',include('apps.operativchaco.urls',namespace='examendiag')),
    path('consultas/', include('apps.consultas.urls', namespace='consultas_api')),
    path('ayuda/', include('apps.ayudarenpe.urls', namespace='ayuda')),
    path('evaluaciones_educativas/', include('apps.evaluaciones_educativas.urls', namespace='evaluaciones_educativas')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

templates/biblioteca/resultados/asistencia_usuario.html
{% extends 'biblioteca/layout_dir.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Card lateral (Filtros) -->
        <div class="col-md-3">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5>Filtros</h5>
                </div>
                <div class="card-body">
                    <form id="filter-form">
                        <!-- CUE Anexo -->
                        <div class="form-group">
                            <label for="cueanexo">Cueanexo:</label>
                            <input type="text" id="cueanexo" name="cueanexo" class="form-control">
                        </div>
                        
                        <!-- Mes -->
                        <div class="form-group">
                            <label for="mes">Mes:</label>
                            <select id="mes" name="mes" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero, nombre in meses %}
                                    <option value="{{ numero }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="nivel">Nivel:</label>
                            <select id="nivel" name="nivel" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero, nombre in niveles %}
                                    <option value="{{ numero }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="usuario">Usuario:</label>
                            <select id="usuario" name="usuario" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero,nombre in usuarios %}
                                    <option value="{{ numero }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="regional">Regional:</label>
                            <select id="regional" name="regional" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero, nombre in regionales %}
                                    <option value="{{ numero }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <!-- Año -->
                        <div class="form-group">
                            <label for="anio">Año:</label>
                            <input type="number" id="anio" name="anio" class="form-control" min="2000" max="2030">
                        </div>                        

                    </form>
                </div>
            </div>
        </div>

        <!-- Card central (Resultados) -->
        <div class="col-md-9">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <h5>Resultados Asistencia de Usuarios</h5>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Cueanexo</th>
                                <th class="text-center">Mes</th>
                                <th class="text-center">Año</th>
                                <th class="text-center">Nivel</th>
                                <th class="text-center">Usuario</th>
                                <th class="text-center">Varones</th>
                                <th class="text-center">Subtotal</th>
                            </tr>
                        </thead>
                        <tbody id="resultados">
                            <!-- Aquí se llenarán los datos dinámicamente -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        function actualizarResultados() {
            var formData = $("#filter-form").serialize(); // Serializar datos del formulario
            
            $.ajax({
                url: "{% url 'bibliotecas:filtrar_asisusua' %}", // Endpoint en Django
                type: "GET",
                data: formData,
                dataType: "json",
                success: function(response) {
                    var tbody = $("#resultados");
                    tbody.empty();

                    if (response.datos.length > 0) {
                        $.each(response.datos, function(index, item) {
                            tbody.append(`
                                <tr>
                                    <td class="text-center">${item.cueanexo}</td>
                                    <td>${item.mes}</td>
                                    <td>${item.anio}</td>
                                    <td>${item.nivel}</td>
                                    <td>${item.usuario}</td>
                                    <td class="text-center">${item.varones}</td>
                                    <td class="text-center">${item.total}</td>
                                </tr>
                            `);
                        });

                        // Agregar fila del total
                        tbody.append(`
                            <tr class="bg-light font-weight-bold">
                                <td colspan="5" class="text-right"><strong>Total:</strong></td>
                                <td class="text-center"><strong>${response.total_varones}</strong></td>
                                <td class="text-center"><strong>${response.total_general}</strong></td>
                            </tr>
                        `);
                    } else {
                        tbody.append('<tr><td colspan="5" class="text-center">No hay datos</td></tr>');
                    }
                }
            });
        }

        // Ejecutar al cambiar un filtro
        $("#filter-form input, #filter-form select").on("change", actualizarResultados);
    });

</script>

{% endblock %}

templates/biblioteca/resultados/informe_pedagogico_gestor.html
{% extends 'biblioteca/layout_gestor.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Card lateral (Filtros) -->
        <div class="col-md-3">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5>Filtros</h5>
                </div>
                <div class="card-body">
                    <form id="filter-form">
                        <!-- CUE Anexo -->
                        <div class="form-group">
                            <label for="cueanexo">Cueanexo:</label>
                            <input type="text" id="cueanexo" name="cueanexo" class="form-control">
                        </div>
                        
                        <!-- Mes -->
                        <div class="form-group">
                            <label for="mes">Mes:</label>
                            <select id="mes" name="mes" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero, nombre in meses %}
                                    <option value="{{ nombre }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="servicio">Servicio:</label>
                            <select id="servicio" name="servicio" class="form-control">
                                <option value="">Seleccione</option>
                                {% for nom_servicio in servicios %}
                                    <option value="{{ nom_servicio }}">{{ nom_servicio }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="regional">Regional:</label>
                            <select id="regional" name="regional" class="form-control">
                                <option value="">Seleccione</option>
                                {% for numero, nombre in regionales %}
                                    <option value="{{ numero }}">{{ nombre }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <!-- Año -->
                        <div class="form-group">
                            <label for="anio">Año:</label>
                            <input type="number" id="anio" name="anio" class="form-control" min="2000" max="2030">
                        </div>                       

                    </form>
                </div>
            </div>
        </div>

        <!-- Card central (Resultados) -->
        <div class="col-md-9">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h5>Resultados Informe Pedagógico</h5>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Cueanexo</th>
                                <th class="text-center">Mes</th>
                                <th class="text-center">Año</th>                                
                                <th class="text-center">Servicio</th>
                                <th class="text-center">Varones</th>
                                <th class="text-center">Subtotal</th>
                            </tr>
                        </thead>
                        <tbody id="resultados">
                            <!-- Aquí se llenarán los datos dinámicamente -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        function actualizarResultados() {
            var formData = $("#filter-form").serialize(); // Serializar datos del formulario
            
            $.ajax({
                url: "{% url 'bibliotecas:filtrar_infopedag' %}", // Endpoint en Django
                type: "GET",
                data: formData,
                dataType: "json",
                success: function(response) {
                    var tbody = $("#resultados");
                    tbody.empty();

                    if (response.datos.length > 0) {
                        $.each(response.datos, function(index, item) {
                            tbody.append(`
                                <tr>
                                    <td class="text-center">${item.cueanexo}</td>
                                    <td>${item.mes}</td>
                                    <td>${item.anio}</td>                                    
                                    <td>${item.nom_servicio}</td>
                                    <td class="text-center">${item.varones}</td>
                                    <td class="text-center">${item.total}</td>
                                </tr>
                            `);
                        });

                        // Agregar fila del total
                        tbody.append(`
                            <tr class="bg-light font-weight-bold">
                                <td colspan="4" class="text-right"><strong>Total:</strong></td>
                                <td class="text-center"><strong>${response.total_varones}</strong></td>
                                <td class="text-center"><strong>${response.total_general}</strong></td>
                            </tr>
                        `);
                    } else {
                        tbody.append('<tr><td colspan="6" class="text-center">No hay datos</td></tr>');
                    }
                }
            });
        }

        // Ejecutar al cambiar un filtro
        $("#filter-form input, #filter-form select").on("change", actualizarResultados);
    });

</script>

{% endblock %}