apps/cenpe/urls.py
from django.urls import path
from .views import DatosPersonalCenpeCreateView, cargar_localidades, DatosAcademicosCenpeCreateView, CargosHorasCenpeCreateView
from .views import obtener_cargos_por_nivel, CargosHorasCenpeListView, EliminarDocentesView, IndexCenpe
from .views_reportes import GenerarCertificado

app_name='cenpe'

urlpatterns = [
    path('',IndexCenpe,name='index'),
    path('crear/', DatosPersonalCenpeCreateView.as_view(), name='crear'),
    path('cargar_localidades/', cargar_localidades, name='cargar_localidades'),
    path('academico/', DatosAcademicosCenpeCreateView.as_view(), name='academico'),
    path('cargo_horas/',CargosHorasCenpeCreateView.as_view(),name='cargo_horas'),
    path('listado/',CargosHorasCenpeListView.as_view(),name='listado'),
    path('obtener-cargos-por-nivel/', obtener_cargos_por_nivel, name='obtener_cargos_por_nivel'),
    path('eliminar/',EliminarDocentesView.as_view(),name='eliminar'),
    path('generar-pdf/', GenerarCertificado, name='generar_pdf'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import RedirectView, TemplateView
from django.views import defaults as default_views
from apps.dashboard.views import directores
from apps.mapas.views2 import mapapuntos, obtenerdatos
from apps.establecimientos.views import establecimientos
from apps.evaluaciones.views import cargar_respuestas, ver_puntajes
from apps.unidadgestion import views_pers_doc_central
from apps.operativoschaco.views import guardar_examen, examen_guardado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('al/',include('apps.alumnos.urls', namespace='al')),
    path('dash/', directores, name='dash'),
    path('director/',include('apps.directores.urls',namespace='director')),
    path('cargar/', include('apps.archivar.urls', namespace='cargar')),
    path('mapoteca/', include('apps.mapoteca.urls', namespace='mapoteca')),
    path('lex/', include('apps.normativa.urls', namespace='lex')),
    path('mapapuntos/', mapapuntos, name='mapapuntos'),
    path('dibujararea/', obtenerdatos, name='dibujararea'),
    path('login/', include('apps.login.urls', namespace='login')),
    path('portada/', include('apps.dashboard.urls', namespace='portada')),
    path('escuelas/', establecimientos, name='escuelas'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),    
    path('favicon.ico', RedirectView.as_view(url='/static/img/favicon.ico')),    
    path('map/', include('apps.mapas.urls', namespace='map')),
    path('usua/', include('apps.usuarios.urls', namespace='usua')),
    path('error_conexion/', TemplateView.as_view(template_name='error_conexion.html'), name='error_conexion'),
    path('consulta_vacia/', TemplateView.as_view(template_name='consulta_vacia.html'), name='consulta_vacia'),
    path('repo/', include('apps.reportes.urls', namespace='repo')),    
    path('videoteca/', include('apps.videoteca.urls', namespace='videoteca')),   
    path('acceso/',include('apps.regacceso.urls', namespace='acceso')),
    path('lect/',include('apps.lectocomp.urls',namespace='lect')),
    path('indicador/',include('apps.indicadores.urls',namespace='indicador')),
    path('doc/',include('apps.asistendoc.urls',namespace='doc')),   
    path('censo/',include('apps.cenpe.urls',namespace='censo')) ,
    path('operativo/',include('apps.oplectura.urls', namespace='operativo')),
    path('super/',include('apps.supervisores.urls', namespace='super')), 
    path('sup/',include('apps.superescuela.urls', namespace='sup')),    
    path('contador/',include('apps.cuenta_regresiva.urls',namespace='contador')),
    path('organica/',include('apps.pof.urls',namespace='organica')),
    path('select2/', include('django_select2.urls')),       
    path('evaluacion/<int:alumno_id>/<int:evaluacion_id>/', cargar_respuestas, name='cargar_respuestas'),
    path('puntajes/<int:alumno_id>/', ver_puntajes, name='ver_puntajes'),
    path('evaluaciones/',include('apps.evaluaciones.urls',namespace='evaluaciones')),
    path('central/',include('apps.unidadgestion.urls',namespace='central')),
    path('uegp/',include('apps.uegp.urls',namespace='uegp')),
    path('chaco/',include('apps.funcionarios.urls',namespace='chaco')),
    path('rl/',include('apps.represlegales.urls',namespace='rl')),
    path('indigena/',include('apps.intercultural.urls',namespace='indigena')),
    path('bbl/',include('apps.biblioteca.urls',namespace='bbl')),
    path('indic/',include('apps.indicadoresie.urls',namespace='indic')),
    path('infra/',include('apps.infraestructura.urls',namespace='infra')), 
    path('pregunta/',include('apps.operativoschaco.urls',namespace='pregunta')), 
    path('examendiag/',include('apps.operativchaco.urls',namespace='examendiag')),
    path('consultas/', include('apps.consultas.urls', namespace='consultas_api')),
    path('ayuda/', include('apps.ayudarenpe.urls', namespace='ayuda')),
    path('evaluaciones_educativas/', include('apps.evaluaciones_educativas.urls', namespace='evaluaciones_educativas')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

apps/cenpe/forms.py
from logging import PlaceHolder
from attr import field
from django import forms
from .models import CeicPuntos, Datos_Personal_Cenpe, Estado_Civil_Cenpe, Gestion_Institucion_Cenpe, Nivel_Formacion_Cenpe, Nivel_Sistema, PadronCenpe, SituacionRevista, Tipo_Formacion_Cenpe, Tipo_Institucion_Cenpe, documento_tipo, nacionalidad, provincia_tipo, localidad_tipo, pais, Academica_Cenpe, sexo_tipo
from .models import CargosHoras_Cenpe, TipoJornada_Cueanexo, Zona_Cueanexo, Categoria_Cueanexo, funciones
from .models import condicionactividad, PadronCenpe
import re

class DatosPersonalCenpeForm(forms.ModelForm):   
    """
    Formulario para capturar los datos personales del usuario del sistema CENPE.

    Campos:
        apellidos (CharField): Campo de texto para el apellido.
        nombres (CharField): Campo de texto para el nombre en mayúsculas.
        dni (CharField): Campo de texto para ingresar el DNI.
        cuil (CharField): Campo de texto para ingresar el CUIL.
        telfijo (CharField): Campo de texto para ingresar el teléfono fijo.
        celular (CharField): Campo de texto para ingresar el número de celular.
        f_nac (DateField): Campo para ingresar la fecha de nacimiento.
        calle (CharField): Campo de texto para la calle de la dirección.
        nro (CharField): Campo de texto para el número de la dirección.
        mz (CharField): Campo de texto para el bloque o manzana.
        pc (CharField): Campo de texto para el código postal.
        casa (CharField): Campo de texto para el número de casa.
        piso (CharField): Campo de texto para el piso de la dirección.
        uf (CharField): Campo de texto para la unidad funcional.
        barrio (CharField): Campo de texto para el barrio.
        pais_nac (ModelChoiceField): Campo de selección para el país de nacimiento.
        nacionalidad (ModelChoiceField): Campo de selección para la nacionalidad.
        t_doc (ModelChoiceField): Campo de selección para el tipo de documento.
        sexo (ModelChoiceField): Campo de selección para el sexo.
        estado_civil (ModelChoiceField): Campo de selección para el estado civil.
        nivel_form (ModelChoiceField): Campo de selección para el nivel de formación alcanzado.
        prov_nac (ModelChoiceField): Campo de selección para la provincia de nacimiento.
        prov_resid (ModelChoiceField): Campo de selección para la provincia de residencia.
        loc_nac (ModelChoiceField): Campo de selección para la localidad de nacimiento.
        loc_resid (ModelChoiceField): Campo de selección para la localidad de residencia.

    Métodos:
        clean_apellidos(): Limpia y valida el campo de apellidos.
        clean_nombres(): Limpia y valida el campo de nombres.
        __init__(): Inicializa el formulario y carga dinámicamente las localidades según la provincia seleccionada.
    """ 
    
    apellidos=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    ) 
    
    nombres=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput', 'placeholder':'Sin abreviaturas, todo en mayúsculas'})
    )
    
    dni=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput','placeholder':'Sin puntos. Ej: 22345678'}),
        
        label='DNI N°'
    )
    
    cuil=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput','placeholder':'Sin puntos ni guiones medios. Ej: 27223456782'}),
        
        label='CUIL N°'
    )
    
    telfijo=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput', 'placeholder':'Sin el 0 del código de área. Ej: 3624123456'}),
        
        label='Teléfono Fijo'
    )    
    
    
    celular=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput', 'placeholder':'Sin el 0 del código de área ni el 15. Ej: 3734123456'}),
        
    )
    
    f_nac=forms.DateField(
        widget=forms.DateInput(attrs={'class':'form-control date', 'type':'date'}),
        
        label='Fecha Nacimiento'
    )
    
    calle=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput', 'placeholder':'Sin abreviaturas, todo en mayúsculas'})
    )   
    
    nro=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    )   
    
    mz=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    ) 
    
    pc=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    )     
    
    casa=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    )  
    
    piso=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    )     
    
    uf=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput'})
    )   
    
    barrio=forms.CharField(
        widget=forms.TextInput(attrs={'class':'form-control textinput', 'placeholder':'Si desconoce/ no tiene, consignar "SIN DATOS"'}),
        
    )   
    
    pais_nac = forms.ModelChoiceField(
        queryset=pais.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        label='País Nacimiento'
    )
    
    nacionalidad = forms.ModelChoiceField(
        queryset=nacionalidad.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'})
    )
    
    t_doc = forms.ModelChoiceField(
        queryset=documento_tipo.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        label='Tipo Documento'
    )      
    
    sexo = forms.ModelChoiceField(
        queryset=sexo_tipo.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'})
    )
    
    estado_civil = forms.ModelChoiceField(
        queryset=Estado_Civil_Cenpe.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'})
    )
    
    nivel_form = forms.ModelChoiceField(
        queryset=Nivel_Formacion_Cenpe.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        help_text='Seleccionar máximo Nivel de Formación Alcanzado',
        label='Nivel Formación'
    )   
    
    
    prov_nac = forms.ModelChoiceField(
        queryset=provincia_tipo.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        label='Provincia Nacimiento'
    )
    
    prov_resid = forms.ModelChoiceField(
        queryset=provincia_tipo.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control select2'}),
        label='Provincia Residencia'
    )

    loc_nac = forms.ModelChoiceField(
        queryset=localidad_tipo.objects.none(),  
        widget=forms.Select(attrs={'class': 'form-control select2'}), 
        label='Localidad Nacimiento'
    )    
    
    
    loc_resid = forms.ModelChoiceField(
        queryset=localidad_tipo.objects.none(),  
        widget=forms.Select(attrs={'class': 'form-control select2'}), 
        label='Localidad Resisdencia'
    )   
    

    class Meta:
        model = Datos_Personal_Cenpe
        fields = '__all__'
        widgets = {
            'usuario': forms.HiddenInput(),  
        }
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['apellidos'].widget.attrs['autofocus']=True
        
        # Si hay una provincia de nacimiento seleccionada, carga las localidades correspondientes
        if 'prov_nac' in self.data:
            try:
                provincia_id = int(self.data.get('prov_nac'))
                print('provincia_id', provincia_id)  
                self.fields['loc_nac'].queryset = localidad_tipo.objects.filter(c_provincia_id=provincia_id).order_by('descripcion_loc')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            
            # Si hay una instancia existente, muestra las localidades correspondientes a la provincia guardada
            self.fields['loc_nac'].queryset = localidad_tipo.objects.filter(c_provincia=self.instance.prov_nac).order_by('descripcion_loc')
        
        # Si hay una provincia de residencia seleccionada, carga las localidades correspondientes
        if 'prov_resid' in self.data:
            try:
                provincia2_id = int(self.data.get('prov_resid'))
                print('provincia2_id', provincia2_id)  
                self.fields['loc_resid'].queryset = localidad_tipo.objects.filter(c_provincia_id=provincia2_id).order_by('descripcion_loc')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            # Si hay una instancia existente, muestra las localidades correspondientes a la provincia guardada
            self.fields['loc_resid'].queryset = localidad_tipo.objects.filter(c_provincia=self.instance.prov_resid).order_by('descripcion_loc')

    def clean_apellidos(self):
        """
        Asegura que el campo de apellidos esté en mayúsculas y solo contenga caracteres válidos.
        
        Returns:
            str: Apellido validado y convertido a mayúsculas.
        """
        
        # Asegura que apellidos esté en mayúsculas y solo contenga caracteres válidos
        apellidos = self.cleaned_data['apellidos'].upper()
        allowed_chars = re.compile(r"^[A-ZÁÉÍÓÚÑ' ]+$")
        if not allowed_chars.match(apellidos):
            raise forms.ValidationError(_('Solo se permiten letras mayúsculas, espacios, tildes y apóstrofes.'))
        return apellidos

    def clean_nombres(self):
        """
        Asegura que el campo de nombres esté en mayúsculas y solo contenga caracteres válidos.
        
        Returns:
            str: Nombre validado y convertido a mayúsculas.
        """
        
        # Asegura que nombres esté en mayúsculas y solo contenga caracteres válidos

templates/cenpe/crear_datos_personales.html
{% extends 'dashboard/bodycenpe.html' %}

{% load static %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Datos Personal Cenpe</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 20px;
        }

        h1 {
            color: #333;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }

        button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .highlighted-paragraph {
            background-color: #f0f8ff; /* Color de fondo */
            border: 1px solid #ccc; /* Borde del recuadro */
            padding: 15px; /* Espacio interno del recuadro */
            border-radius: 5px; /* Bordes redondeados */
            margin-bottom: 20px; /* Espacio debajo del párrafo */
            font-weight: bold;
        }
        /* Estilos del modal */
        .modal {
            display: none;
            position: fixed;
            z-index: 1050;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            overflow: auto; /* Permite desplazamiento si el contenido es largo */
            background: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        }

        .modal.show {
            display: flex;
        }

        .modal-dialog {
            background: white;
            border-radius: 8px;
            max-width: 90%;
            width: 600px;
            margin: 20px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .modal-header,
        .modal-footer {
            padding: 15px;
            border-bottom: 1px solid #ddd;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .modal-footer {
            border-top: 1px solid #ddd;
            border-bottom: none;
        }

        .modal-body {
            padding: 15px;
            max-height: 60vh; /* Limita la altura del contenido */
            overflow-y: auto; /* Agrega scroll si el contenido es demasiado largo */
        }

        .modal-title {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }

        @media (max-width: 600px) {
            .modal-dialog {
                width: 95%;
                margin: 10px;
            }

            .modal-body {
                max-height: 50vh;
            }
        }
    </style>
    <!-- Asegúrate de cargar jQuery antes que Select2 -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script> 
    
</head>
<body>
    <h1>Datos Personales ReNPEE</h1>
    <p class="highlighted-paragraph">
        Declaro bajo juramento que todos los datos consignados son veraces. Asimismo, me notifico que cualquier falsedad u omisión dará motivo a las sanciones disciplinarias previstas.
    </p>
    <form method="post">
        {% csrf_token %}
        <table>   
            <tr>                
                <td>{{ form.usuario }}</td>
            </tr>         
            <tr>
                <td>{{ form.apellidos.label_tag }}</td>
                <td>{{ form.apellidos }}</td>
            </tr>
            <tr>
                <td>{{ form.nombres.label_tag }}</td>
                <td>{{ form.nombres }}</td>
            </tr>
            <tr>
                <td>{{ form.dni.label_tag }}</td>
                <td>{{ form.dni }}</td>
            </tr>
            <tr>
                <td>{{ form.cuil.label_tag }}</td>
                <td>{{ form.cuil }}</td>
            </tr>
            <tr>
                <td>{{ form.telfijo.label_tag }}</td>
                <td>{{ form.telfijo }}</td>
            </tr>
            <tr>
                <td>{{ form.celular.label_tag }}</td>
                <td>{{ form.celular }}</td>
            </tr>
            <tr>
                <td>{{ form.f_nac.label_tag }}</td>
                <td>{{ form.f_nac }}</td>
            </tr>
            <tr>
                <td>{{ form.pais_nac.label_tag }}</td>
                <td>{{ form.pais_nac }}</td>
            </tr>
            <tr>
                <td>{{ form.nacionalidad.label_tag }}</td>
                <td>{{ form.nacionalidad }}</td>
            </tr>
            <tr>
                <td>{{ form.t_doc.label_tag }}</td>
                <td>{{ form.t_doc }}</td>
            </tr>
            <tr>
                <td>{{ form.sexo.label_tag }}</td>
                <td>{{ form.sexo }}</td>
            </tr>
            <tr>
                <td>{{ form.estado_civil.label_tag }}</td>
                <td>{{ form.estado_civil }}</td>
            </tr>
            <tr>
                <td>{{ form.nivel_form.label_tag }}</td>
                <td>{{ form.nivel_form }}</td>
            </tr>
            <tr>
                <td>{{ form.prov_nac.label_tag }}</td>
                <td>{{ form.prov_nac }}</td>
            </tr>
            <tr>
                <td>{{ form.loc_nac.label_tag }}</td>
                <td>{{ form.loc_nac }}</td>
            </tr>
            <tr>
                <td>{{ form.prov_resid.label_tag }}</td>
                <td>{{ form.prov_resid }}</td>
            </tr>
            <tr>
                <td>{{ form.loc_resid.label_tag }}</td>
                <td>{{ form.loc_resid }}</td>
            </tr>
            <tr>
                <td>{{ form.calle.label_tag }}</td>
                <td>{{ form.calle }}</td>
            </tr>
            <tr>
                <td>{{ form.nro.label_tag }}</td>
                <td>{{ form.nro }}</td>
            </tr>
            <tr>
                <td>{{ form.mz.label_tag }}</td>
                <td>{{ form.mz }}</td>
            </tr>
            <tr>
                <td>{{ form.pc.label_tag }}</td>
                <td>{{ form.pc }}</td>
            </tr>
            <tr>
                <td>{{ form.casa.label_tag }}</td>
                <td>{{ form.casa }}</td>
            </tr>
            <tr>
                <td>{{ form.piso.label_tag }}</td>
                <td>{{ form.piso }}</td>
            </tr>
            <tr>
                <td>{{ form.uf.label_tag }}</td>
                <td>{{ form.uf }}</td>
            </tr>
            <tr>
                <td>{{ form.barrio.label_tag }}</td>
                <td>{{ form.barrio }}</td>
            </tr>            

        </table>
        {% if form.errors %}
            <div class="errors">
                {{ form.errors }}
            </div>
        {% endif %}
        <button type="submit">Guardar</button>
    </form>
    <!-- Modal de confirmación -->
    <div id="confirmModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirmar Datos Personales</h5>
                    <button type="button" class="close corregir-button" aria-label="Cerrar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Por favor, verifica los datos ingresados:</p>
                    <ul id="modalDataList"></ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary corregir-button">Corregir</button>
                    <button type="button" id="confirmButton" class="btn btn-primary">Confirmar</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            // Inicializa Select2
            $('.select2').select2();

            // Maneja el cambio en los selects de provincias
            $('#id_prov_nac').change(function() {
                var provinciaId = $(this).val(); 
                $.ajax({
                    url: "{% url 'cenpe:cargar_localidades' %}",
                    data: {'provincia_id': provinciaId},
                    success: function(data) {
                        $("#id_loc_nac").empty().append('<option value="">Seleccione una localidad</option>');
                        $.each(data, function(key, value) {
                            $("#id_loc_nac").append('<option value="' + value.id + '">' + value.descripcion + '</option>');
                        });
                        $('#id_loc_nac').trigger('change.select2');
                    },
                    error: function(xhr, status, error) {
                        console.error('Error al cargar localidades:', error);
                    }
                });
            });

            $('#id_prov_resid').change(function() {
                var provincia2Id = $(this).val(); 
                $.ajax({
                    url: "{% url 'cenpe:cargar_localidades' %}",
                    data: {'provincia_id': provincia2Id},
                    success: function(data) {
                        $("#id_loc_resid").empty().append('<option value="">Seleccione una localidad</option>');
                        $.each(data, function(key, value) {
                            $("#id_loc_resid").append('<option value="' + value.id + '">' + value.descripcion + '</option>');
                        });
                        $('#id_loc_resid').trigger('change.select2');
                    },
                    error: function(xhr, status, error) {
                        console.error('Error al cargar localidades:', error);
                    }
                });
            });

            // Captura el evento submit del formulario para evitar el envío inmediato
            $('form').on('submit', function(event) {
                event.preventDefault(); // Previene el envío del formulario

                // Llenar el modal con los datos del formulario
                let dataList = $('#modalDataList');
                dataList.empty();

                // Recorre cada campo del formulario y muestra sus valores
                $(this).find('input, select, textarea').each(function() {
                    let label = $(this).closest('tr').find('td:first-child').text(); // Obtiene la etiqueta asociada
                    let value;

                    if ($(this).is('select')) {
                        value = $(this).find('option:selected').text(); // Captura el texto seleccionado en los selects
                    } else if ($(this).is(':checkbox')) {
                        value = $(this).is(':checked') ? 'Sí' : 'No'; // Indica si el checkbox está marcado o no
                    } else {
                        value = $(this).val(); // Captura el valor de los inputs y textareas
                    }

                    if (label && value) {
                        dataList.append(`<li><strong>${label}:</strong> ${value}</li>`); // Muestra la etiqueta y el valor
                    }
                });

                // Mostrar el modal
                $('#confirmModal').addClass('show');
            });

            // Botón Confirmar: envía el formulario
            $('#confirmButton').click(function() {
                $('form')[0].submit(); // Envía el formulario original
            });

            // Botón Corregir: cierra el modal
            $('.corregir-button').click(function() {
                $('#confirmModal').removeClass('show'); // Cierra el modal al quitar la clase 'show'
            });
        });
    </script>


</body>
{% endblock %}

templates/cenpe/indexcenpe.html
{% extends 'dashboard/bodycenpe.html'%}

{% load static %}

{% block content %}

    <style>
        .logo-container {
            text-align: center; 
            margin: 20px 0;
        }

        .logo-image {
            max-width: 600px; 
            height: auto; 
        }
    </style>
    <div class="logo-container">    
        <img src="{% static 'img/relevamientodocente2024.jpeg' %}" alt="Logo" class="logo-image">
    </div>

{% endblock %}